### ISSUE TITLE
Show background in the bookmarks

### ISSUE THREAD

**Issue by Chamrosh** [Zonnev/elementaryos-firefox#1]
![screenshot from 2019-02-11 15 32 35](https://user-images.githubusercontent.com/10561726/52561995-49906680-2e12-11e9-9cf6-5e32efedb92e.png)

**Comment by Zonnev** [comment]
Thank you for noticing this bug! I changed it. 

What I see in your screenshot is that you are maybe running my fork of the elementary firefox theme of Harvey. I don't update my fork at Harvey's theme. Sorry... 

Please use my theme on [this page](https://github.com/Zonnev/elementaryos-firefox) without the title bar on. I have updated the userChrome.css file. You can now move the new tab button (+) to the left of the tabs bar as well.
