### ISSUE TITLE
Drop-down menu out of place

### ISSUE THREAD

**Issue by irondave** [Zonnev/elementaryos-firefox#12]
The drop-down menu out of place.
I attach these screenshots as examples.
![schermata da 2019-02-16 14-11-21](https://user-images.githubusercontent.com/8292014/52900429-e75ea980-31f5-11e9-82d6-fc2e41ec397b.png)
![schermata da 2019-02-16 14-15-25](https://user-images.githubusercontent.com/8292014/52900431-ef1e4e00-31f5-11e9-8398-72cb45c38d9b.png)
![schermata da 2019-02-16 14-08-15](https://user-images.githubusercontent.com/8292014/52900435-fe9d9700-31f5-11e9-9e7e-eaf70060f78f.png)
![schermata da 2019-02-16 14-07-34](https://user-images.githubusercontent.com/8292014/52900437-02c9b480-31f6-11e9-86d3-1e1bdb2d6285.png)

**Comment by Zonnev** [comment]
This problem was posted before by someone else. This is not a problem of this theme. It's in your Firefox.
