### ISSUE TITLE
[Dark mode] Dark text in selection boxes in customization panel 

### ISSUE THREAD

**Issue by TheSirC** [Zonnev/elementaryos-firefox#14]
In the customization panel, in dark mode, the selection boxes (and I suspect elsewhere) have similar color making them unreadable. 

![Screenshot of the bug](https://user-images.githubusercontent.com/11771227/52912725-77175d00-32b5-11e9-9f94-ac55f5b41087.png)

**Comment by Manueljlin** [comment]
Also happens on the site security window:
![screen record from 2019-02-25 20 42 45](https://user-images.githubusercontent.com/11275573/53364061-4df26e80-393e-11e9-9530-3114adb7333d.gif)

**Comment by Zonnev** [comment]
@Manueljlin I think this is because I changed the main window background colour. I will look into it, trying to not change dialog windows backgrounds. Thanks for discovering this bug.

**Comment by Zonnev** [comment]
@Manueljlin I sort of fixed it, all texts are readable but page info looks kind of ugly now... Make sure you download the latest userChrome to see the fix.

**Comment by Zonnev** [comment]
@Manueljlin I did now fixed it, page info looks normal again in the latest release of userChrome.

**Comment by Manueljlin** [comment]
Thanks
