### ISSUE TITLE
The headerbar changes color

### ISSUE THREAD

**Issue by Manueljlin** [Zonnev/elementaryos-firefox#17]
(FF65 on elementaryOS 5.0 Juno)
Happens when:
     1. Pressing any Fn key (e.g. F8)
     2. Dragging anything (e.g. links, text, images, etc)
     3. _Unfocusing_ the window (hope I wrote that correctly)
![gif](https://user-images.githubusercontent.com/11275573/53364146-77ab9580-393e-11e9-8a10-3ec793c3e0b0.gif)

**Comment by Manueljlin** [comment]
Video:
https://i.imgur.com/60nqMj2.gif

**Comment by Zonnev** [comment]
Thank you for this bug. It has something to do with the main-window colouring, I will look into it.

**Comment by Zonnev** [comment]
I made the colours change when Firefox is unfocused. So its default behaviour now.

**Comment by Manueljlin** [comment]
While it transitions from the gradient to the inactive color, there's some weird blinking. I'll try to look for a way to fix it.

**Comment by Zonnev** [comment]
Isn't the blinking because you pressed the F8 button a couple of times? Each time you press the button, you go out of Firefox / Firefox is unfocused.
