### ISSUE TITLE
Tabs are larger than Epiphany

### ISSUE THREAD

**Issue by Hedronmx** [Zonnev/elementaryos-firefox#18]
I have attached screenshots that show this.
![Imgur](https://i.imgur.com/2rkFq1h.png)
![Imgur](https://i.imgur.com/I3nO7Hi.png)

I tried changing the tab width but couldn't figure out how the calculation was done

**Comment by Zonnev** [comment]
Its fixed, tabs width are same size as Epiphany.

**Comment by Zonnev** [comment]
Seems it isn't fixed, the tabs move to different positions when selecting dark mode.

**Comment by Zonnev** [comment]
I changed back the tab width in the latest userChrome. It seems there is a bug in Firefox which makes this strange behaviour of tabs skipping to different positions when changing the tab width.

**Comment by Vento09** [comment]
I don't like the Epiphany's tab width. In Elementary OS, all applications, which use tabs, are larger than Epiphany.

![abas](https://user-images.githubusercontent.com/30022019/53494127-c4e15180-3a7b-11e9-8ab0-24bc0a32429f.png)
[1º Firefox; 2ºEpiphany; 3º Files; 4º Terminal; 5º Code]

See picture that Files, Terminal and Code's tab is larger than Epiphany and Firefox. 

I've tried to change the width to stay like them and I've noticed that tabs was skipping to different positions. So I have changed userChrome.css from line 273 and it works :smile: 

> #tabbrowser-tabs {
   display: block;
   width: calc(100vw - 100px) !important;/**/
 }
 /* tabs width */
 .tabbrowser-tab:not([pinned]) {
    width: 180px !important;
   min-width: 50px !important;
}

**Comment by Hedronmx** [comment]
> I don't like the Epiphany's tab width. In Elementary OS, all applications, which use tabs, are larger than Epiphany.
> 
> ![abas](https://user-images.githubusercontent.com/30022019/53494127-c4e15180-3a7b-11e9-8ab0-24bc0a32429f.png)
> [1º Firefox; 2ºEpiphany; 3º Files; 4º Terminal; 5º Code]
> 
> See picture that Files, Terminal and Code's tab is larger than Epiphany and Firefox.
> 
> I've tried to change the width to stay like them and I've noticed that tabs was skipping to different positions. So I have changed userChrome.css from line 273 and it works smile
> 
> > #tabbrowser-tabs {
> > display: block;
> > width: calc(100vw - 100px) !important;/**/
> > }
> > /* tabs width */
> > .tabbrowser-tab:not([pinned]) {
> > width: 180px !important;
> > min-width: 50px !important;
> > }

It works!! Looks nice!

**Comment by Zonnev** [comment]
@Vento09 Thanks for solving it. I will remove the calculation width as well since block takes the whole width anyways. ))

**Comment by Hedronmx** [comment]
I did some further modifications to the titlebar you can see the comparison below.

![Imgur](https://i.imgur.com/DlmpLHh.png)

I changed back, forward and refresh padding, url bar margins and close button offset
How do I share these changes?

You can see the changes here. It already includes the code from Vento09
https://www.diffchecker.com/NQfk3LIi

**Comment by Zonnev** [comment]
@Hedronmx You are styling the navigation buttons to Epiphany which has different padding than the default elementary gtk theme. I like to keep it the way it is now but thank you for sharing your adjustments.

**Comment by Zonnev** [comment]
Since adding display:block wasn't a perfect solution, because the tabs close button sometimes didn't appear, I found a better solution:

`.tabbrowser-tab[fadein]:not([pinned]) {
  max-width: 180px !important;
}` 

So this issue is completely fixed now ))
