### ISSUE TITLE
No rounded corners on the headerbar

### ISSUE THREAD

**Issue by Chamrosh** [Zonnev/elementaryos-firefox#2]
![screenshot from 2019-02-12 17 59 31](https://user-images.githubusercontent.com/10561726/52642464-4bc8f280-2ef0-11e9-8754-4d4953989fae.png)

**Comment by Zonnev** [comment]
Hello, I have noticed this as well but it seems impossible to make those rounded corners. The main window, where all elements are settled, does not have the option to make rounded corners. We have to wait for this option to be possible.

**Comment by Zonnev** [comment]
I think I managed to make the rounded corners. You can download the [new release](https://github.com/Zonnev/elementaryos-firefox/releases/tag/v65.3) and see it for yourself. I hope you like it.
