### ISSUE TITLE
some button position problem

### ISSUE THREAD

**Issue by mIcHyAmRaNe** [Zonnev/elementaryos-firefox#21]
hello, i really appreciate your theme even if it has some small bugs :) 

there are **no margin** between `maximize button` and `menu button`
as we can see in screenshots bellow: 

- maximized:
![Screenshot from 2019-03-13 10 22 38](https://user-images.githubusercontent.com/17873513/54268139-d7c74c00-457a-11e9-8a45-32efe7cb495d.png)

- minimized:
![Screenshot from 2019-03-13 10 23 44](https://user-images.githubusercontent.com/17873513/54268142-d85fe280-457a-11e9-8975-c68b0fe50e90.png)

also, when we hover `close button` and `maximize button` it change their place and go a little bit to the top ( should stay **vertical-align: center;** )

**Comment by Zonnev** [comment]
Seems you have been fiddling with userChrome a bit. The window control buttons are set over the nav-bar, they don't push away nav-bar items. To adjust the spacing of the nav-bar items you should adjust padding in line 135. To keep the window control buttons in place (not moving around), you should only remove line 108.

**Comment by mIcHyAmRaNe** [comment]
i didn't edit userChrome, as i didn't upgrade my browser (i forgot that important detail ^^) 
problem resolved after updating firefox to the latest version 65.0.1 

thank you anyway
