### ISSUE TITLE
Tab overflows out of tab bar in unmaximized window

### ISSUE THREAD

**Issue by arshubham** [Zonnev/elementaryos-firefox#3]
Firefox 67.0.a1
![image](https://user-images.githubusercontent.com/14235191/52723990-8e63fb00-2fd4-11e9-87d1-81118cba449b.png)

Shown correctly when windows in maximized

**Comment by Zonnev** [comment]
Hello, you probably have drag space on in the customization panel.

**Comment by arshubham** [comment]
Thanks. Disabling drag space did the trick. You might want to add it in the README

**Comment by Zonnev** [comment]
Done it, thank you for the suggestion.

**Comment by Zonnev** [comment]
I have fixed it in release [v65.9](https://github.com/Zonnev/elementaryos-firefox/releases/tag/v65.9)
