### ISSUE TITLE
Invert color for text selection in menubar

### ISSUE THREAD

**Issue by arshubham** [Zonnev/elementaryos-firefox#6]
Might look better with white text with blue background. That is what other gtk apps do.
![image](https://user-images.githubusercontent.com/14235191/52733359-8d3cc900-2fe8-11e9-9ab7-a982de21b402.png)

**Comment by Zonnev** [comment]
Hmm seems the background gradient of the url bar is making this effect. If there is no gradient, the url bar looks less like an elementary design.

**Comment by Zonnev** [comment]
It's fixed on the [newest release](https://github.com/Zonnev/elementaryos-firefox/releases) of this theme. Thanks for noticing this bug.
