### ISSUE TITLE
New tab button doesn't work when on left of the tabs

### ISSUE THREAD

**Issue by arshubham** [Zonnev/elementaryos-firefox#7]
When new tab button is on left of the tabs and container tabs are enabled from the preferences. New tab button opens the container context menu instead of opening a new tab. Also looks smaller in size when on right side.

Firefox 67.0.a1

Edit: Sorry, meant to right 67. I am on the latest nightly too

**Comment by Zonnev** [comment]
I will see if I can resize the new tab button when its on the right side. I have, aside from testing the theme only on Firefox 65, also Firefox Nightly installed with container tab enabled and the themed new tab button just opens new tabs. I'm sorry to say that I'm not testing on earlier releases of Firefox and will not do so.

**Comment by Zonnev** [comment]
I have resized the new tab button when its on the right side of the tabs. I have also deleted some extra id's for the new tab button, so maybe it doesn't show the container menu anymore. Install [the latest release](https://github.com/Zonnev/elementaryos-firefox/releases/tag/v65.7), please.

**Comment by Zonnev** [comment]
I see now what you mean: After you moved the new tab button to the left, clicking it shows the menu.  After a restart of Firefox, its gone. Strange behaviour. I will try to fix it, but release it when Firefox 67 is released as well. As soon as I fixed it I will post the fixed userChrome.css in this issue topic.

**Comment by Zonnev** [comment]
I fixed it this issue in [latest release](https://github.com/Zonnev/elementaryos-firefox/releases/tag/v65.8).
