### ISSUE TITLE
Context menu is not aligned to cursor

### ISSUE THREAD

**Issue by dastorm** [Zonnev/elementaryos-firefox#8]
The context menu (either while typing in a text field or right clicking on the screen) is not aligned with the cursor, screenshots attached.
![schermata del 2019-02-15 10 15 10](https://user-images.githubusercontent.com/39257353/52846920-23691000-310b-11e9-83ca-ea86d4f66786.png)
![schermata del 2019-02-15 10 16 38](https://user-images.githubusercontent.com/39257353/52846926-27952d80-310b-11e9-949d-19d91b498d2f.png)

**Comment by Zonnev** [comment]
Which version of Firefox are you using? I don't have this problem with Firefox 65.

**Comment by dastorm** [comment]
Firefox 65 on elementary os 5. But I booted it up again just to be sure and it's not doing it anymore. I also just found this question [here](https://elementaryos.stackexchange.com/questions/18272/firefox-dropdowns-in-wrong-location) on the elementary stack exchange site. So could it just be a coincidence that it started doing it while using the theme?

**Comment by Zonnev** [comment]
Please remove the userChrome.css and leave it in your trash. start up Firefox and see if it still happens with the default theme on. After you checked you can undo the removal of userChrome.css from the trash.

**Comment by dastorm** [comment]
Apparently it does... I'm sorry for having bothered you with this, I didn't see it happen before and jumped to conclusions to early
![schermata da 2019-02-15 17-08-59](https://user-images.githubusercontent.com/39257353/52868742-6d221c80-3144-11e9-948e-200211207823.png)

**Comment by Zonnev** [comment]
No worries, it's ok! Good luck finding a solution.
